sudo: false
env:
  matrix:
  - BROWSER=chromium EXT=zip
  - BROWSER=firefox EXT=xpi
before_script:
  - npm install -g jpm
script: ./tools/make-${BROWSER}.sh all
deploy:
  provider: releases
  api_key:
    secure: oZs64DJH6O8vrk/7/H4nBv2v9fSsXAqDBgcohK5l1tOFbHyro/qxU5TFav+hN5H3MNCnVuefhHulCGRGvbjYFUKxh3sCKyBEg+fuqLK4YPOx0PA5Amhy1wubCekCyX/EPr1trN2SQNNsRYsT2YEfqlQvS+aXHKhBdLikAqeZkMe3eBJfwGrDzOdf8iADGPcAiZSL4ZzEaM8CX/OGzJBV16kBZj2jfdzYNYM5sRyqjtIrxWUq/cZmvEJr1H19Q5RaUxJthmu14lw9iL8R5T5+jPt0dXxTMnkWcdDZ7lx7oUDt+PUrboE2LwDkgidoi1uEp7TvIZtFaAKNKe2PGMAlrqQDf+Nppay2YTxcOlcWYGK0autVN741jECEc1GiYESgTsTP6ZmWp6glCzJLhM4RemOBNNkPap/+x3fZ9k0Jl8xZGmcv/09TjxKtBttEkT2oD/f1Yg/xDnqLpp2GLMLjLgABlq9FMG3xrsLrnqRM+zDCf9ulDx/7ARsuV8WZ5URvLQymoA4eVLqNlnZ7ElLgGyyVAFvNqbYPruhJ4izB7CT6gvnQ1Jk85Vs0Q8a7oSaoPHG7LEWblnw09UOYLWllWReV5YBVSqUJfe6RE5r0cWZoH/Q9Lz1tM/d/0sLtkMyS2zADKoon42OWkv4tID6cC95EwxgjGzf/FjEFkyup1vU=
  file: dist/build/scrummer.${BROWSER}.${EXT}
  skip_cleanup: true
  on:
    repo: foucdeg/scrummer
    tags: true
    all_branches: true
